### ISSUE TITLE
tiss@data

### ISSUE THREAD

**Issue by Malarkey73** [jaleesr/BITFAM#1]
Hi
I couldn't get this to work. Error is 
**Error in Seurat::FindVariableFeatures(tiss@data) : 
  object 'tiss' not found**

BITFAM code contain the line 
**variable_genes <- Seurat::FindVariableFeatures(tiss@data)**

shouldn't that just be ?
**variable_genes <- Seurat::FindVariableFeatures(data)**

**Comment by jaleesr** [comment]
Hi, 

Thank you for using our tool! Yes, you are right. It should be data in the function. The "data" here should be a seurat object. If you are using raw data as inout, please run BITFAM_preprocess first?

**Comment by jaleesr** [comment]
@Malarkey73 Please let us know if your issue is resolved. If not, we will gladly provide more suggestions.
