### ISSUE TITLE
Multiple samples

### ISSUE THREAD

**Issue by Sabermea** [jaleesr/BITFAM#2]
I was wondering if it makes sense to merge multiple samples such as control and stimulation and then run BITFAM on the merged object. Thank you!

**Comment by jaleesr** [comment]
Thank you for your interest in on our model! Technically, the answer is yes. You can integrate the two datasets using the Seurat function: merge or IntegrateData. Then input the normalized data to BITFAM.

But please note that this of course depends on the question you are asking. If you are primarily interested in the difference between control and stimulation, and comparing the varying inferred TF activities, then this would be a valid approach.  Let us know if you have more questions.  We will gladly help.

**Comment by Sabermea** [comment]
Thank you for your prompt reply! Yes, the goal is to compare TF activities between control and treatment. I was under the impression that normalization in Seurat is not required and can be done using BITFAM_preprocess function. Thank you!

**Comment by jaleesr** [comment]
Yes. you can input count matrix to BITFAM. You need some way to merge the data at least. You could use cbind to concatenate the matrices from the two condition. Please make sure the order of genes are matched to each other.
