### ISSUE TITLE
Picking a license?

### ISSUE THREAD

**Issue by tomsing1** [jaleesr/BITFAM#3]
Thanks a lot for making th the BITFAM method available. It seems the DESCRIPTION file still contains the boilerplate code from the [usethis](https://usethis.r-lib.org/) package that can be run to specify a license:

https://github.com/jaleesr/BITFAM/blob/62b8b7656608f448c9c95145e1deebb6fa1c0aaf/DESCRIPTION#L11

Perhaps you can pick a license to be explicit about use & reuse of the codebase?
Many thanks in advance!

**Comment by jaleesr** [comment]
Hello. We just added the license in the description file. Thank you for using our package and pointing out this problem! If you have more questions, feel free to contact us.

**Comment by jaleesr** [comment]
@tomsing1 We picked the MIT license, in case this helps.

Thanks!

**Comment by tomsing1** [comment]
Perfect, thanks a lot!
