### ISSUE TITLE
Error while using BITFAM: Sys.setenv(R_MAKEVARS_USER = NULL) : wrong length for argument

### ISSUE THREAD

**Issue by sesemina** [jaleesr/BITFAM#4]
Hi! 
I tried to use BITFAM on scRNa seq data following your instructions. However I received an error after:
BITFAM_res <- BITFAM(data = mtx_preprocess, species = "human", scATAC_obj = NA, ncores = parallel::detectCores()) 

Error in Sys.setenv(R_MAKEVARS_USER = NULL) : wrong length for argument
In addition: Warning message:
In .warn_march_makevars() :
  Detected -march=native in the Makevars file at 'C:/Users/semina/Documents/.R/Makevars'. Compiling with the -march=native flag on windows with Rtools can cause crashes because of the compiler implementation. rstan will ignore the Makevars file until -march=native is removed. You can disable this by setting rstan_options(disable_march_warning = TRUE)

**Comment by sgao30** [comment]
It seems like your configuration of C++ has some problems. Could you please reinstall it? This [link](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain) may help. Let me know if you still get errors. Thank you!
