### ISSUE TITLE
BITFAM doesn't run parallel

### ISSUE THREAD

**Issue by VergaJU** [jaleesr/BITFAM#6]
Thanks to all the group for the interesting package

I am trying to run BITFAM with my single-cell RNA-Seq dataset following the instruction provided in the GitHub pages
It looks running correctly but even if I specify in the arguments to use all the cores of my machine, it looks like running with a single core:

```
BITFAM_res <- BITFAM(data = data_matrix_normalized, species = "human", scATAC_obj = NA, ncores = parallel::detectCores())
```
![Screenshot from 2023-03-13 15-18-39](https://user-images.githubusercontent.com/94962245/224746599-85c85a7c-3f72-4a2f-8851-5e5f8c4123cf.png)

I tested it on my local machine and on a remote VM but the result is always the same. I also try to use `BiocParallel` but the `BPPARAM` parameter wasn't used. Is there anything I am missing or that I can do to parallelize the computation?

EDIT:
I tested BiocParallel to verify that I use more than a CPU per time and it worked, and this is the warning I receive when I run BITFAM:
```
rstan (Version 2.21.8, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
```
Thanks for the help
Jacopo

**Comment by sgao30** [comment]
Dear Jacopo,

Thank you for using our tool! The variational bayes function (vb) in Rstan does not support multi-cores. The part that using multi-cores is initializing the model which is before the VB is running. 

Please let us know if you have other questions. Thank you!

Best regards,
Shang
