### ISSUE TITLE
interseted_TFs

### ISSUE THREAD

**Issue by jziggles** [jaleesr/BITFAM#9]
Hello - I have been using BITFAM and it has been great, thanks.  I am working on human data and trying to use the interseted TF option though this does not seem to be working currently - below is the line of code.  Please let me know thanks.

BITFAM_res <- BITFAM(data = data_matrix_normalized, interseted_TF = c("IRF3", "IRF7"), species = "human", scATAC_obj = NA, ncores = parallel::detectCores())

**Comment by sgao30** [comment]
Hi,
Thank you for using our tool!
What is the error you have? Currently, IRF7 is not in the TF ChIP-seq database. So you cannot do the inference on IRF7. If you have IRF7 ChIP-seq data or IRF7 target gene list, you can put it into the extdata folder. Please let me know if you need more help!

**Comment by liezeltamon** [comment]
Hi @sgao30, I think the above problem is related to this issue #16  I posted last year. I guess the checking for NA in interseted_TF throws an error if interseted_TF is a vector of elements. Would be nice to fix the checking of NAs so we can input multiple TFs of interest. 

Thank you!
